# Generated by Django 2.2 on 2019-04-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190414_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['-data_publicacao'], 'verbose_name_plural': 'Postagens'},
        ),
    ]
