# Generated by Django 2.2 on 2019-04-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postagem_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens'),
        ),
    ]
