# Generated by Django 2.2 on 2019-04-17 19:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190414_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment_autor', models.CharField(max_length=40)),
                ('coment_texto', models.TextField()),
                ('coment_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de publicação')),
                ('id_postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Postagem')),
            ],
            options={
                'verbose_name': 'Comentário',
                'ordering': ['-coment_publicacao'],
            },
        ),
    ]
