# Generated by Django 2.2 on 2019-04-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='id_postagem',
            new_name='post_ref',
        ),
    ]
